### ISSUE TITLE
feature request - Logastash 5.x compatibility

### ISSUE THREAD

**Issue by RemiSlv** [connamara/logstash-filter-fix_protocol#71]
Hi,
Thanks for the great plugin. It's working like I charm on logstash 2.x

Do you have any plan to port it on LS 5.x ?

R

**Comment by daino3** [comment]
Hi Remi,

Thanks for the reminder! I'll be busy for the next few weeks, so if this is time-sensitive feel free to submit a PR if you're up for it :). 

Happy Holidays.

**Comment by lief480** [comment]
Any update on this?

**Comment by kenned3** [comment]
I'm also interested in seeing this on Logstash 5.0

tried to install it and seems some versioniong issues?  Is this a matter of just updating the GEM file to reference a newer logstash-core?

Validating logstash-filter-fix_protocol
Installing logstash-filter-fix_protocol
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.1.2)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.1.2) java

    logstash-filter-fix_protocol (>= 0) java depends on
      logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-core (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by daino3** [comment]
Hi folks. 

I just freed up to work on this. I have an open PR and will be working through any issues in the near term.

**Comment by daino3** [comment]
closing this. please reopen or create a new issue if gem version 0.3.0 doesn't work for your 5x installed version of Logstash.
