### ISSUE TITLE
Support for multiple Fix protocols

### ISSUE THREAD

**Issue by kmalyar-tic** [connamara/logstash-filter-fix_protocol#75]
Hi,

I'm relatively new to FIX log parsing.  I was asked to look into it.  We get messages in 4.2/4.4/5.  I have a data dictionaries, but i don't want to just hack up an xml document. 

Is there a way to set up filters in logstash to support each type?

**Comment by daino3** [comment]
Hi @kmalyar-tic. 

I have not personally tried parsing different FIX versions with a single Logstash instance - I'll add this as a feature. That being said, I believe you could run separate Logstash instances, each with its own configuration file to accomplish what you're trying to do. 

https://discuss.elastic.co/t/multiple-logstash-instances-on-single-server/28947

**Comment by kmalyar-tic** [comment]
Hi @daino3 

Thanks for the quick response.

I'll definitely look into doing that, if that is the proper way (or only way at the moment).  I appreciate the feature request.

One question, just to follow up.  Looking at it, couldn't I make 3 FIX filters and grok for the fix version in each log message, letting me use 1 instance?

Its all coming from the same file, so I'm not sure how it would behave with 3 instances pointed at it.

**Comment by daino3** [comment]
If it's all coming from a single FIX input and going to a single output, I _think_ you should be able to do that, yes. If you get it to work, would you mind submitting a PR with an update to the README with an example configuration file you got to work? That would be super helpful for others.

**Comment by kmalyar-tic** [comment]
I’d be happy to do that.

I’ll let you know how it goes.

**Comment by kmalyar-tic** [comment]
#76 Added it here

**Comment by daino3** [comment]
@cbusbey this is closed per #76 - please close the issue.

**Comment by daino3** [comment]
@cbusbey - please close.
