### ISSUE TITLE
Parsing 552 <NoSides> incorrectly

### ISSUE THREAD

**Issue by kmalyar-tic** [connamara/logstash-filter-fix_protocol#83]
Hi @daino3 ,

So we are still chugging away.  We have encountered an issue.  It looks like for tag 552 it is pulling a bunch of inappropriate tags into a nested group when it shouldn't

eg:

http://www.quickfixengine.org/FIX44.xml
![image](https://user-images.githubusercontent.com/12397078/30075915-4a9b6b5c-9245-11e7-9349-827755872c92.png)

But in the actual parsing of a message:
![image](https://user-images.githubusercontent.com/12397078/30076008-950531b4-9245-11e7-8474-1e6809aa770b.png)

the actual fix message that caused this:
"8=FIX.4.4\u00019=458\u000135=AE\u000134=1613\u000149=blablabla-blablabla\u000156=blablabla-blablabla\u000152=20170831-18:56:45.294\u0001571=LSZUFPPS49391601999999795\u0001568=tcr-2017-08-30-17-05-23\u0001150=F\u000139=2\u000117=blablabla\u0001570=N\u000155=USD/MXN\u0001167=FOR\u000138=6000000.000000\u00016054=106931160.000000\u000144=17.821860\u000132=blablabla.000000\u000131=99.99\u0001194=99.99\u0001195=0.0000\u000175=20170831\u00016215=SP\u000160=20170831-18:56:45.294\u0001552=1\u000154=1\u000137=blablabla\u0001453=1\u0001448=blablabla\u0001447=D\u0001452=11\u00011=blablabla blablabla blablabla-blablabla NA\u000115=USD\u000140=D\u0001487=0\u000164=20170905\u000110=002\u0001"

Any chance you can help us out?

So far its an awesome plugin!

Regards,
Kelvin

**Comment by daino3** [comment]
thank you for the bug report, @kmalyar-tic. I will try to get to it this week.

**Comment by cbusbey** [comment]
@kmalyar-tic can you try grabbing the latest quickfix-jruby gem and trying again?  This version includes quickfixj 1.6.4, which might correct the issue you are seeing.

**Comment by kmalyar-tic** [comment]
@cbusbey, I came in and tried to do as you suggested.  Unfortunately, i'm getting bitten by not really understanding the ruby development environment.  I tried installing the plugin again (hoping it would trigger an update of the gem) no luck.

I tried this:
```

 ~/tmp/logstash [] $ gem list

*** LOCAL GEMS ***

bundler-unload (1.0.2)
did_you_mean (default: 1.0.1)
executable-hooks (1.3.2)
gem-wrappers (1.3.0)
jar-dependencies (default: 0.3.9)
jruby-openssl (0.9.20 java, 0.9.18 java)
jruby-readline (1.1.1 java)
json (1.8.3 java)
minitest (default: 5.4.1)
net-telnet (default: 0.1.1)
power_assert (default: 0.2.3)
psych (2.2.2 java)
racc (1.4.14 java)
rake (12.0.0, default: 10.4.2)
rdoc (default: 4.2.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
test-unit (default: 3.1.1)
 ~/tmp/logstash [] $ ls
bin           config        data     Gemfile.jruby-1.9.lock  LICENSE  logstash-core             NOTICE.TXT  sample.conf
CHANGELOG.md  CONTRIBUTORS  Gemfile  lib                     logs     logstash-core-plugin-api  path2       vendor

```

No joy,  can you give me the dummy's guide to how I would grab the latest version (I try not to ask the same question twice though if its any consolation).

**Comment by cbusbey** [comment]
Taking a closer look at the message, I believe the plugin is working as expected.  NoSides is a repeating group in message type AE (and for all messages that use it in the FIX44 spec for that matter).   The FIX field value of NoSides may be 1 or 2, but a value of 1 indicates there is one group, 2 indicates there are two.  The logstash plugin appropriately converts this to an array of group objects.  If you want the value of NoSides, this is the length of the NoSides array that gets produced by the plugin.

**Comment by daino3** [comment]
thanks for taking care of this @cbusbey! 🥇

**Comment by kmalyar-tic** [comment]
Wait
my pipeline is completely broken trying to follow advice, can someone help me out with thel atest? although this doesn't make any sense to me.

Thanks
Kelvin

**Comment by daino3** [comment]
@kmalyar-tic:

The error you're seeing is due to correctly installing quickfix-jruby 1.6.5. To have your gem revert to 1.6.0, simply uninstall 1.6.5.

```
gem uninstall quickfix-jruby --version 1.6.5
```
You can confirm you're using 1.6.0 with:
```
gem list quickfix-jruby
```

**Comment by kmalyar-tic** [comment]
`
 ~ [] $ gem uninstall quickfix-jruby --version 1.6.5
 ~ [] $ gem list quickfix-jruby

*** LOCAL GEMS ***


 ~ [] $
`

**Comment by daino3** [comment]
```
gem install quickfix-jruby --version 1.6.0
```

**Comment by kmalyar-tic** [comment]
@daino3 

If you check in the comment, I did that before running it (and it breaking)
